
version: '3'
services:
  api:
    container_name: example-api-container
    build: api/.
    entrypoint: python3 -m flask run --host=0.0.0.0
    env_file:
      - api/.env
    ports:
      - '5000:5000'