import pytest

from api.utils.data_management import parse_sample_data, insert_sample_data
from api.app import create_app
from api.db import init_db

@pytest.fixture(scope="module")
def client():
    app = create_app(mode="testing")
    app.config['TESTING'] = True # verbose error logging

    with app.test_client() as client:
        with app.app_context():
            yield client

@pytest.fixture(scope="module")
def data():
    TEST_DATA = {
        "raw": '''>lcl|NC_026943.1_cds_YP_009134731.1_1 [gene=NS3] [locus_tag=AAW66_gp1] [db_xref=GeneID:24248404] [protein=non-structural protein 3] [protein_id=YP_009134731.1] [location=385..1296] [gbkey=CDS]
        ATGGCTTGCGTATACGGTATTGAGAACTGTGATCATACAAAGTGTTTTCGCTGTGGAGAGTGCACTAGAG
        GCAGTCAAGTACATAGACTTTGTTATTCCAACATTACAGAGGAAGACTATGCGATATCACAGTTGCTTGC
        CAGTAGTACAGAGTGTCTACCTACAGAAAGCGACGAAGAAACAGCAGACCAGATACGCTCAGATACGCCA
        ATCAGTATGCAGGTACAAGAGTATCTCGATTGGGAGAATACTGCTCTATTTTCGACAACATACCGCTTTC
        ATACATACTGGACACACTTTTATGGCGATCGTGAGGAGATTGATTCAGATTATAGTACTCCTGAGGCTAG
        TGATGAGGATAGTCAATCACTGCTAAGGAACAAGATTAAAGTACATAGGTATCTTACAAGTGAAATGACT
        GCACGAGAATTTTTTCTTGCAAATAGAGACTTTGATATTGATGTTTTGTGTTTGCCAGATGATTCTCTTA
        TTAGAATGCGACTTGGTACAGTGACAAAATTTGATCCTATTGCTAAACAACATTTTGTGTATCATAAAGA
        GTGTATTGATCCTGAACAATTTCATTTGACAGAAAAAGGATTCAGTAAAGCTGTTCTTTCAGTAAAAGCA
        ACAAATAAGAATGCATTTATCTCATTAATTGAAGATCTGTTGTTTACATTTTTTTGTCAGGAGTGTAAGA
        AATTTATTTTTCATACAGTGGAGTATATGGAAGATAGTGTATGGAAATTACCAAATGAAAACATCTGGCC
        AGACTGCAAACATCTTTTATATAATTGTCACTTACTTTATGATTTAAATACTTATGTGAATTTGAAAGGA
        CATAAATTAATTGCTACTGTTTCACCGCAGGAACCACCAACGAAACGGCAACGCCTAGAATTCCATGAAT
        AA
        >lcl|NC_026943.1_cds_YP_009134732.1_2 [gene=NS1] [locus_tag=AAW66_gp2] [db_xref=GeneID:24248403] [protein=non-structural protein 1] [protein_id=YP_009134732.1] [location=1289..3028] [gbkey=CDS]
        ATGAATAATGTCCAAGAGGAAGCTGGAAGAGATGTCACCAGAACACGAAACGGAGGAAGAGGAGGACTCG
        GAACCAGAAAGAGAAGAAGATCGGACTCTGGAGAAAGACGGAATGACAGCGGGACCGAAGATATCGTTCA
        CAGCGATGTTGCGGAGAATACTACAGGCGAACTTACCGTTGAGCCAAGTACATCCGGGCTATCTACTGGG
        ATTCGTGACGATGATGACGGGAGAGACCAATCTACCAGTAGAACTAGAGAACTCCCTGTATGGTTTTCAA
        AAAGCGGGCCAGATATGGAACAACGGTATTGGAAAGGCTTCAAAGAAAGGTGTGATAGAATACTTACAGA
        GCTGCAAAACTCTGATGGGCAGTTGGTTCGCGACATCTTTCGATTCGAAGACCCTAGAGAGTATGATGAC
        TTTATTAGATGCATACAACGAGACACAAATTACAGAAGAGGACTGCTCCAGGTATGTCGCGAAGATAGTC
        ACATCCACGTCGTGCACGACTGCACCTTCAGCAACGGAATGTGCCGGTGCGACTGGTACAAAAAGGCGAA
        AACCTACGGGGCACACCTTAGACGAGATAAACGTTCTCATCGACGAAATTCCTGTAGAAGTAGAACCGCA
        ACCGACATTCAAAACCTACTCTTCTATTATTGCACGAAAGGACGACAAATTGTATATCAAAAAATTCGAG
        GACAGCTGGAAAGAATACCAAGTGAAGGTTACAATCTATCGACGTCAAGACTTAATGGACTGTCCGAATA
        CTTCAGAGAAATGGCACTACAAATACCAGGAGATGGACCTGAATTACAACAGTGGGAGCCAGATTTGGAA
        GTTGATGAGCCAGCTGAAGTACCAACAAATGGAGTACCTCAACGAAAAAAACGTAAAATGGGTGCCCAAG
        AAAGAATACAGCTAAAGACAGTTGAGTTGCTGGAATTGTATCCCATATGTCCTCCAGAAGCTATAGTAAA
        ACATAGGATTTGGAGATGTGATCCAGAGCTGAGATTTAAGAATGTAAATGATAAAGAAATTAGAAATGCT
        ATTTCTAGTTTCAAGGATACACTGACCACTTATTCAATGAATGAATATCAGAAAATGTACAATAATCCTG
        ATTGTATACCTATATTTAGTGCTGGTTATGGGAATTATGAGACTTATTATTATAATGTTGAAAATAGCCT
        CAAAATTATGGATGAACTGGTTAATTACCAGTGTGGTGGAGATGAAGAGGCTATCATTGATTTTGTGACT
        ACTTTATATAATGTGTTGGAACGTAAAGTTCCTAAATTGAACTGCATTGTAATTCACTCACCTCCCAGTG
        CGGGGAAGAATTTCTTTTTTGATGCAGTAAAGGACTATTATTTGAATTGTGGCCATCTATGTAATGCAAA
        TAAATATAATAATTTTCCATTTCAAGATGCAGAAGGCAGAAGAATTGTACTGTGGAATGAACCAAACTAT
        GCTCCAGAATTTCTGGAACAGATCAAAGAAATACTAGGTGGAGACTCCACTAGTGTAAATGTAAAGTATC
        AAAGTGATACTCCTGTGTATCGTACACCTGTGATTGTACTGACAAATAATAAGGTTTCATTCATGAATCA
        TTCTGCCTTCATTGATAGGATTAGGGTGTTTAACTGGATGGCTGCACCATTTTTAGCACAGTATAAGAAG
        AAGCCAAATCCATTGGCAGTATATGACTTCTTTAAGAAGTATAAATTGGTGGAAGGGTAA''',
        "target": 'ATGAATAATGTCCAAGAGGAAGCTGGAAGAGATGTCACCAGAACACGAAACGGAGGAAGAGGAGGACTCGGAACCAGAAAGAGAAGAAGATCGGACTCTGGAGAAAGACGGAATGACAGCGGGACCGAAGATATCGTTCA',
        "match": 'TTGAATAATGTCCAAGAGGAAGCTGGAAGAGATGTCACCAGAACACGAAACGGAGGAAGAGGAGGACTCGGAACCAGAAAGAGAAGAAGATCGGACTCTGGAGAAAGACGGAATGACAGCGGGACCGAAGATATCGTTCA',
        "no-match-too-short": 'ATGATAATGTCCAAGAGGAAGCTGGAAGAGATGTCACCAGAACACGAAACGGAGGAAGAGGAGGACTCGGAACCAGAAAGAGAAGAAGATCGGACTCTGGAGAAAGACGGAATGACAGCGGGACCGAAGATATCGTTCA',
        "no-match-too-distant": 'ATGAATAATGTCCAAGAGGAACTAGGAAGAGATGTCACCAGAACACGAAACGGAGGAAGAGGAGGACTCGGAACCAGAAAGAGAAGAAGATCGGACTCTGGAGAAAGACGGAATGACAGCGGGACCGAAGATATCGTTCA',
        "api-input-match": "ATGAATAATGTCCAAGAGGAAGCTGGAAGAGATGTCACCAGAACACGAAACGGAGGAAGAGGAGGACTCGGAACCAGAAAGAGAAGAAGATCGGACTCTGGAGAAAGACGGAATGACAGCGGGACCGAAGATATCGTTCACAGCGATGTTGCGGAGAATACTACAGGCGAACTTACCGTTGAGCCAAGTACATCCGGGCTATCTACTGGGATTCGTGACGATGATGACGGGAGAGACCAATCTACCAGTAGAACTAGAGAACTCCCTGTATGGTTTTCAAAAAGCGGGCCAGATATGGAACAACGGTATTGGAAAGGCTTCAAAGAAAGGTGTGATAGAATACTTACAGAGCTGCAAAACTCTGATGGGCAGTTGGTTCGCGACATCTTTCGATTCGAAGACCCTAGAGAGTATGATGACTTTATTAGATGCATACAACGAGACACAAATTACAGAAGAGGACTGCTCCAGGTATGTCGCGAAGATAGTCACATCCACGTCGTGCACGACTGCACCTTCAGCAACGGAATGTGCCGGTGCGACTGGTACAAAAAGGCGAAAACCTACGGGGCACACCTTAGACGAGATAAACGTTCTCATCGACGAAATTCCTGTAGAAGTAGAACCGCAACCGACATTCAAAACCTACTCTTCTATTATTGCACGAAAGGACGACAAATTGTATATCAAAAAATTCGAGGACAGCTGGAAAGAATACCAAGTGAAGGTTACAATCTATCGACGTCAAGACTTAATGGACTGTCCGAATACTTCAGAGAAATGGCACTACAAATACCAGGAGATGGACCTGAATTACAACAGTGGGAGCCAGATTTGGAAGTTGATGAGCCAGCTGAAGTACCAACAAATGGAGTACCTCAACGAAAAAAACGTAAAATGGGTGCCCAAGAAAGAATACAGCTAAAGACAGTTGAGTTGCTGGAATTGTATCCCATATGTCCTCCAGAAGCTATAGTAAAACATAGGATTTGGAGATGTGATCCAGAGCTGAGATTTAAGAATGTAAATGATAAAGAAATTAGAAATGCTATTTCTAGTTTCAAGGATACACTGACCACTTATTCAATGAATGAATATCAGAAAATGTACAATAATCCTGATTGTATACCTATATTTAGTGCTGGTTATGGGAATTATGAGACTTATTATTATAATGTTGAAAATAGCCTCAAAATTATGGATGAACTGGTTAATTACCAGTGTGGTGGAGATGAAGAGGCTATCATTGATTTTGTGACTACTTTATATAATGTGTTGGAACGTAAAGTTCCTAAATTGAACTGCATTGTAATTCACTCACCTCCCAGTGCGGGGAAGAATTTCTTTTTTGATGCAGTAAAGGACTATTATTTGAATTGTGGCCATCTATGTAATGCAAATAAATATAATAATTTTCCATTTCAAGATGCAGAAGGCAGAAGAATTGTACTGTGGAATGAACCAAACTATGCTCCAGAATTTCTGGAACAGATCAAAGAAATACTAGGTGGAGACTCCACTAGTGTAAATGTAAAGTATCAAAGTGATACTCCTGTGTATCGTACACCTGTGATTGTACTGACAAATAATAAGGTTTCATTCATGAATCATTCTGCCTTCATTGATAGGATTAGGGTGTTTAACTGGATGGCTGCACCATTTTTAGCACAGTATAAGAAGAAGCCAAATCCATTGGCAGTATATGACTTCTTTAAGAAGTATAAATTGGTGGAAGGGTAG"
    }

    return TEST_DATA
